---
title: "Teja's Tech Hub"
description: A dynamic portfolio showcasing cutting-edge projects and innovations.
url: "https://teja.github.io"

collections:
  projects:
    output: true
    permalink: "/project/:slug/"

plugins:
  # GitHub Pages supported plugins
  - jekyll-feed

markdown: kramdown

# Custom variables if needed
author: Teja Mathukumalli
github_username: teja
